set nocompatible
filetype off
set encoding=utf8
syntax on

" Code
set tabstop=4
set hlsearch
" Colors for putty etc
if $TERM == "xterm-256color"
	set t_Co=256
endif

" Remove trailing whitespace
fun! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

autocmd BufWritePre * :call TrimWhiteSpace()

" Vim-Plug
call plug#begin()

" Vim-airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" NerdTree
Plug 'https://github.com/scrooloose/nerdtree.git'
" NerdCommenter
Plug 'scrooloose/nerdcommenter'

call plug#end() " Les plugins doivent etre ajoutes avant cette luigne

filetype plugin on

" Vim airline config
let g:airline_powerline_fonts = 0 
